# Generated by Django 6.0.7 on 2026-07-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='starting_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='engine.node'),
        ),
    ]
